#!/usr/bin/env node

// Check if help is requested
if (process.argv.includes('--help') || process.argv.includes('-h')) {
  console.log('🚚 IC SPICY Logistics API Setup Script');
  console.log('=====================================');
  console.log('');
  console.log('This script helps you configure your IC SPICY Logistics API integration.');
  console.log('');
  console.log('Usage:');
  console.log('  node setup_logistics_api.js');
  console.log('');
  console.log('The script will prompt you for:');
  console.log('  - Your API key from https://icspicy-logistics-ynt.caffeine.xyz');
  console.log('  - Environment settings (development/staging/production)');
  console.log('  - Debug mode preferences');
  console.log('');
  console.log('After setup, restart your development server to apply changes.');
  process.exit(0);
}

/**
 * IC SPICY Logistics API Setup Script
 * 
 * This script helps you set up the environment variables needed for the logistics API integration.
 * Run this script to configure your API key and other settings.
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

async function setupLogisticsAPI() {
  console.log('🚚 IC SPICY Logistics API Setup');
  console.log('================================');
  console.log('');

  try {
    // Get API key from user
    const apiKey = await question('Enter your IC SPICY Logistics API key: ');
    
    if (!apiKey || apiKey.trim() === '') {
      console.log('❌ API key is required. Please run the script again with a valid API key.');
      process.exit(1);
    }

    // Get environment preference
    const environment = await question('Environment (development/staging/production) [production]: ') || 'production';
    
    // Get debug preference
    const debugMode = await question('Enable debug mode? (y/n) [n]: ');
    const enableDebug = debugMode.toLowerCase() === 'y' || debugMode.toLowerCase() === 'yes';

    // Create .env content
    const envContent = `# IC SPICY Logistics API Configuration
# Generated by setup script on ${new Date().toISOString()}

# Logistics API Configuration
REACT_APP_LOGISTICS_API_KEY=${apiKey.trim()}
REACT_APP_LOGISTICS_BASE_URL=https://icspicy-logistics-ynt.caffeine.xyz/api/v1
REACT_APP_LOGISTICS_ENVIRONMENT=${environment}
REACT_APP_ENABLE_LOGISTICS_SYNC=true
REACT_APP_DEBUG_LOGISTICS=${enableDebug ? 'true' : 'false'}

# Optional: Additional configuration
REACT_APP_LOGISTICS_TIMEOUT=30000
REACT_APP_LOGISTICS_RETRY_ATTEMPTS=3

# Development settings (uncomment for local development)
${environment === 'development' ? '' : '# '}REACT_APP_DEBUG_LOGISTICS=true
${environment === 'development' ? '' : '# '}REACT_APP_LOGISTICS_ENVIRONMENT=development
`;

    // Write .env file
    const envPath = path.join(__dirname, '.env');
    fs.writeFileSync(envPath, envContent);

    console.log('');
    console.log('✅ Setup completed successfully!');
    console.log('');
    console.log('📝 Configuration saved to .env file:');
    console.log(`   - API Key: ${apiKey.substring(0, 8)}...${apiKey.substring(apiKey.length - 4)}`);
    console.log(`   - Environment: ${environment}`);
    console.log(`   - Debug Mode: ${enableDebug ? 'enabled' : 'disabled'}`);
    console.log(`   - Base URL: https://icspicy-logistics-ynt.caffeine.xyz/api/v1`);
    console.log('');
    console.log('🚀 Next steps:');
    console.log('   1. Restart your development server if it\'s running');
    console.log('   2. Navigate to the Logistics page in your dapp');
    console.log('   3. Check the browser console for connection status');
    console.log('');
    console.log('💡 Tips:');
    console.log('   - Keep your API key secure and never commit it to version control');
    console.log('   - Use environment-specific API keys for different deployments');
    console.log('   - Enable debug mode during development for detailed logging');

  } catch (error) {
    console.error('❌ Setup failed:', error.message);
    process.exit(1);
  } finally {
    rl.close();
  }
}

// Create .env.example file
const exampleContent = `# IC SPICY Logistics API Configuration Example
# Copy this file to .env and fill in your actual values

# Logistics API Configuration
REACT_APP_LOGISTICS_API_KEY=your-actual-api-key-here
REACT_APP_LOGISTICS_BASE_URL=https://icspicy-logistics-ynt.caffeine.xyz/api/v1
REACT_APP_LOGISTICS_ENVIRONMENT=production
REACT_APP_ENABLE_LOGISTICS_SYNC=true
REACT_APP_DEBUG_LOGISTICS=false

# Optional: Additional configuration
REACT_APP_LOGISTICS_TIMEOUT=30000
REACT_APP_LOGISTICS_RETRY_ATTEMPTS=3

# Development settings (uncomment for local development)
# REACT_APP_DEBUG_LOGISTICS=true
# REACT_APP_LOGISTICS_ENVIRONMENT=development
`;

try {
  fs.writeFileSync(path.join(__dirname, '.env.example'), exampleContent);
  console.log('📄 Created .env.example file for reference');
} catch (error) {
  console.warn('⚠️ Could not create .env.example file:', error.message);
}

setupLogisticsAPI();
